GLOBAL:
    TIMEZONE: "Europe/Berlin"
    LOGFILE: "/home/asset-manager/logs/jetconf.log"
#    LOGFILE: "-"
    PIDFILE: "/tmp/jetconf.pid"
    PERSISTENT_CHANGES: true
    LOG_LEVEL: "debug"
    LOG_DBG_MODULES: ["usr_conf_data_handlers", "nacm", "data"]
    YANG_LIB_DIR: "/home/asset-manager/software/asset-jetconf/yang-modules"
    DATA_JSON_FILE: "/home/asset-manager/logs/ds-dump.json"
    BACKEND_PACKAGE: "jetconf_asset"

HTTP_SERVER:
    DOC_ROOT: "doc-root"
    DOC_DEFAULT_NAME: "index.html"
    API_ROOT: "/restconf"
    SERVER_NAME: "jetconf-h2"
    SERVER_SSL_CERT: "/home/asset-manager/software/asset-jetconf/utils/cert_gen/server_assetmgt.crt"
    SERVER_SSL_PRIVKEY: "/home/asset-manager/software/asset-jetconf/utils/cert_gen/server_assetmgt.key"
    CA_CERT: "/home/asset-manager/software/asset-jetconf/utils/cert_gen/ca.pem"

NACM:
    ENABLED: true
    ALLOWED_USERS: ["analyst@bsi.corp"]
